/**
 * Auto-generated by openapi-typescript from the backend OpenAPI spec.
 * DO NOT EDIT MANUALLY.
 *
 * Regenerate: npm run api:types (requires backend running on localhost:8000)
 *
 * This is a placeholder until the backend is available for type generation.
 */

export interface paths {
	'/health': {
		get: {
			responses: {
				200: {
					content: {
						'application/json': { status: string };
					};
				};
			};
		};
	};
}

export interface components {
	schemas: Record<string, never>;
}
